[project]
name = "notebooks"
version = "0.1.0"
description = "Tutorial notebooks using Open Targets Platform Data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pyspark>=3.5.0,<4.0.0",
]
