name: Generate README

on:
  workflow_dispatch:
  push:
    paths:
      - 'examples/*.ipynb'
      - 'utils/readme.py'
      - 'Makefile'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate README
        run: make readme

      - name: Commit and push README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README [skip ci]" || echo "No changes to commit"
          git push